<?php require __DIR__ . "../../layout/header.phtml"; ?>

<div id="login">
    <div class="container-fluid">
        <div class="card-main-login" style="margin-top: 120px;">
            <div class="d-flex justify-content-center">
                <div class="card shadow-sm" style="width: 30rem;">
                    <div class="card-body">
                        <p class="card-text text-center" style="text-align: center; font-size: 30px;">ระบบ</p>
                        <form id="login-main" method="POST">
                            <div class="form-floating mb-4 mt-4">
                                <input type="text" class="form-control" id="username" v-model="login.username" placeholder="Username">
                                <label for="username">Username</label>
                            </div>
                            <div class="form-floating mb-4 mt-4">
                                <input type="text" class="form-control" id="password" v-model="login.password" placeholder="Password">
                                <label for="password">Password</label>
                            </div>
                            <button type="button" class="button btn-login btn-singin" @click="loginJWT">เข้าสู่ระบบ</button>
                            <br>
                            <p class="lh-base text-center" style="margin-top: 30px;">
                                สร้างบัญชีหรือไม่ <a href="/jwt/register" class="text-decoration-none">ลงทะเบียนที่นี้</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?= asset('js/jwt/loginMainJWT.js') ?>"></script>
<?php require __DIR__ . "../../layout/footer.phtml"; ?>

