<?php require __DIR__ . "../../layout/header.phtml"; ?>
<div class="container-fluid">
    <div class="card-main-register" style="margin-top: 100px;">
        <div class="d-flex justify-content-center">
            <div class="card shadow-sm" style="width: 30rem;">
                <div class="card-body">
                    <p class="card-text text-center" style="text-align: center; font-size: 30px;">ลงทะเบียน / </p>
                    <form id="register-main">
                        <input type="hidden" id="register-url" name="registerURL" value="">
                        <div class="form-floating mb-4 mt-4">
                            <input type="text" class="form-control" id="username" v-model="login.username" placeholder="Username">
                            <label for="username">Username</label>
                        </div>
                        <div class="form-floating mb-4 mt-4">
                            <input type="password" class="form-control" id="password" v-model="login.password" placeholder="Password">
                            <label for="password">Password</label>
                        </div>
                        <button type="submit" class="button btn-register-main btn-register" @click="registerJWT">ลงทะเบียน</button>
                        <br>
                        <p class="lh-base text-center" style="margin-top: 30px;">
                            <a id="back-login-url" href="/jwt/login" class="text-decoration-none">กลับสู่หน้าเข้าสู่ระบบ</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require __DIR__ . "../../layout/footer.phtml"; ?>

<script src="<?= asset('js/jwt/registerMainJWT.js') ?>"></script>